# Generated by Django 3.0.5 on 2020-04-04 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validated', models.BooleanField(verbose_name='Validált')),
                ('zip', models.CharField(max_length=10, verbose_name='Irányítószám')),
                ('age', models.IntegerField(verbose_name='Kor')),
                ('country_code', models.CharField(max_length=2, verbose_name='Ország kód')),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('duration_days', models.IntegerField()),
                ('fixed_symptom', models.CharField(max_length=30)),
                ('related_text', models.CharField(max_length=50)),
                ('related_val', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diarybase.Reporter')),
            ],
        ),
        migrations.CreateModel(
            name='EpidemicActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_actvity', models.CharField(max_length=100)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diarybase.Reporter')),
            ],
        ),
    ]
