# Generated by Django 3.0.5 on 2020-04-05 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('validated', models.BooleanField(default=False, verbose_name='Validált')),
                ('zip', models.CharField(max_length=10, verbose_name='Irányítószám')),
                ('age', models.IntegerField(verbose_name='Kora')),
                ('country_code', models.CharField(default='HU', max_length=2, verbose_name='Ország kód')),
                ('sex', models.CharField(choices=[('M', 'Férfi'), ('F', 'Nő')], default='F', max_length=1, verbose_name='Neme')),
                ('smoking', models.CharField(choices=[('Never', 'sohasem'), ('Earlier', 'korábban'), ('Casual', 'alkalmanként'), ('Regular', 'naponta')], max_length=10, verbose_name='Dohányzik')),
                ('cronic_illnes', models.BooleanField(verbose_name='Krónikus alapbetegség')),
                ('flu_shot', models.BooleanField(verbose_name='Idei influenzaoltás')),
                ('living_with_high_risk_condition', models.BooleanField(verbose_name='veszélyeztetettel (pl idős, krónikus beteg) él együtt')),
                ('liwing_with_high_risk_ocupation', models.BooleanField(verbose_name='fertőződésnek kitettel (pl egészségügyi dolgozó) él együtt')),
            ],
        ),
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('duration_days', models.IntegerField()),
                ('body_temperature', models.CharField(choices=[('N', 'normál testhőmérséklet: 36-37 °C'), ('E', 'Hőemelkedés: 37-38 °C'), ('F', 'Láz: 38-39 °C'), ('H', 'Magas láz: 39 °C felett')], max_length=1, verbose_name='Láz/Hőemelkedés')),
                ('fatigue', models.BooleanField(verbose_name='Levertség')),
                ('cold_shivers', models.BooleanField(verbose_name='Hidegrázás')),
                ('coughing', models.CharField(choices=[('N', 'nincs'), ('D', 'száraz'), ('C', 'hurutos')], max_length=1, verbose_name='Köhögés')),
                ('sore_throat', models.BooleanField(verbose_name='Torokfájás')),
                ('runny_nose', models.BooleanField(verbose_name='Orrfolyás')),
                ('breathing_difficulty', models.BooleanField(verbose_name='Nehézlégzés')),
                ('headache', models.BooleanField(verbose_name='Fejfájás')),
                ('joint_pain', models.BooleanField(verbose_name='Izületi és végtagfájdalmak')),
                ('abdominal_complaint', models.BooleanField(verbose_name='Hasmenés, hasi panaszok')),
                ('decreased_smell_and_taste', models.BooleanField(verbose_name='Csökkent szaglás, ízlelés')),
                ('other_symptom', models.CharField(max_length=50, verbose_name='Egyéb tünet')),
                ('overal_quality', models.IntegerField(verbose_name='Összességében hogy érzi magát egészségileg')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='symptoms', to='diarybase.Reporter')),
            ],
        ),
        migrations.CreateModel(
            name='EpidemicActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_actvity', models.CharField(max_length=100)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='epidemic_activities', to='diarybase.Reporter')),
            ],
        ),
    ]
